workflows:
  android-build:
    name: Android APK Build
    environment:
      vars:
        GRADLEW_PATH: "./gradlew"
      android:
        image: latest
    scripts:
      - echo "Iniciando a compilação do APK..."
      - chmod +x $GRADLEW_PATH
      - $GRADLEW_PATH clean assembleDebug
    artifacts:
      - build/app/outputs/apk/debug/*.apk
