workflows:
  android-build:
    name: Android APK Build
    environment:
      vars:
        GRADLEW_PATH: "./gradlew"
      java: oracle-jdk-17
    scripts:
      - echo "Iniciando a compilação do APK..."
      - chmod +x $GRADLEW_PATH
      - $GRADLEW_PATH clean assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
